<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="355" started-at="2017-04-11T07:02:03Z" finished-at="2017-04-11T07:02:03Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="355" started-at="2017-04-11T07:02:03Z" finished-at="2017-04-11T07:02:03Z">
      <class name="testnglearning.DataDriven">
        <test-method status="FAIL" signature="Addition(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:testnglearning.DataDriven@23ceabc1]" name="Addition" duration-ms="310" started-at="2017-04-11T12:32:03Z" data-provider="testdata" finished-at="2017-04-11T12:32:03Z">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
The data provider is trying to pass 2 parameters but the method testnglearning.DataDriven#Addition takes 3 and TestNG is unable in inject a suitable object]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
The data provider is trying to pass 2 parameters but the method testnglearning.DataDriven#Addition takes 3 and TestNG is unable in inject a suitable object
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1249)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1118)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 2
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1245)
	... 17 more
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Addition -->
      </class> <!-- testnglearning.DataDriven -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
